# Generated by Django 2.1.8 on 2019-08-21 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190821_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
