# Generated by Django 2.1.8 on 2019-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190821_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='age',
        ),
        migrations.AddField(
            model_name='user_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
