# Generated by Django 2.1.8 on 2019-08-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190821_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='relation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
