# Generated by Django 2.1.8 on 2019-08-22 15:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190822_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomps', models.CharField(max_length=500)),
                ('diseases', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
