# Generated by Django 2.1.8 on 2019-08-25 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_data',
            name='enddate',
            field=models.DateField(default=datetime.date(2019, 9, 24)),
        ),
    ]
