# Generated by Django 2.1.8 on 2019-08-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190825_0522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscriptions',
            new_name='subscription_plans',
        ),
    ]
