# Generated by Django 2.1.8 on 2019-08-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190825_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='danger_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='doctor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
