# Generated by Django 2.1.8 on 2019-08-26 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190825_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='common_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account_data',
            name='enddate',
            field=models.DateField(default=datetime.date(2019, 9, 25)),
        ),
    ]
