# Generated by Django 2.1.8 on 2019-09-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190902_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_data',
            name='plan_reports',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='account_data',
            name='plan_subusers',
            field=models.IntegerField(default=5),
        ),
    ]
