# Generated by Django 2.1.8 on 2019-11-19 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190925_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='usocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account_data',
            name='enddate',
            field=models.DateField(default=datetime.date(2019, 12, 19)),
        ),
    ]
