# Generated by Django 2.1.8 on 2019-08-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_symptomps_sent_qa', models.IntegerField(default=5)),
                ('N_symptomps_sent_in_search', models.IntegerField(default=5)),
            ],
        ),
    ]
