# Generated by Django 2.2.2 on 2019-08-18 07:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('temp', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, null=True)),
                ('scode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_mails.templates')),
            ],
        ),
    ]
