# Generated by Django 2.1.8 on 2019-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='scode',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='templates',
            old_name='scode',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='templates',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
