# Generated by Django 2.1.8 on 2019-08-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mails', '0002_auto_20190818_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='templates',
        ),
    ]
