# Generated by Django 2.1.8 on 2019-08-18 08:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('e_mails', '0003_auto_20190818_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('temp', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='e_mails.templates'),
        ),
    ]
