# Generated by Django 2.1.8 on 2019-09-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_mails', '0004_auto_20190818_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.DeleteModel(
            name='content',
        ),
    ]
