# Generated by Django 2.1.8 on 2019-08-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscriptions',
        ),
    ]
