# Generated by Django 2.1.8 on 2019-08-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='report_count',
        ),
    ]
