# Generated by Django 2.1.8 on 2019-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190819_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
