# Generated by Django 2.1.8 on 2019-08-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
