# Generated by Django 2.1.8 on 2019-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190818_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='pregnancy',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
