# Generated by Django 2.1.8 on 2019-08-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190819_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='report_count',
            new_name='allowed_reports',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enddate',
            field=models.DateField(default=datetime.date(2019, 9, 20)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_name',
            field=models.CharField(default='Free', max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registrationdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='report_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reports_allowed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='startdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subuser_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subusers_allowed',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='allowed_subusers',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='extension_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='infinate_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='infinate_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='infinate_subusers',
            field=models.BooleanField(default=False),
        ),
    ]
