# Generated by Django 2.1.8 on 2019-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190819_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pregnancy',
            field=models.BooleanField(),
        ),
    ]
