# Generated by Django 2.1.8 on 2019-08-21 13:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190821_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_count', models.IntegerField(default=0)),
                ('startdate', models.DateField(default=datetime.date.today)),
                ('enddate', models.DateField(default=datetime.date(2019, 9, 20))),
                ('registrationdate', models.DateField(default=datetime.date.today)),
                ('date_check', models.BooleanField(default=True)),
                ('reports_allowed', models.IntegerField(default=5)),
                ('report_check', models.BooleanField(default=True)),
                ('subusers_allowed', models.IntegerField(default=5)),
                ('subuser_check', models.BooleanField(default=True)),
                ('plan_name', models.CharField(default='Free', max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_check',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registrationdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='report_check',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='report_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reports_allowed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subuser_check',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subusers_allowed',
        ),
        migrations.AddField(
            model_name='account_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
