# Generated by Django 2.1.8 on 2019-08-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190819_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='account_key',
            field=models.IntegerField(),
        ),
    ]
