# Generated by Django 2.1.8 on 2019-08-19 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190819_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='account_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
