# Generated by Django 2.1.8 on 2019-08-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190821_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_data',
            name='user',
        ),
    ]
